### ISSUE TITLE
Assembly line crashes at startup

### ISSUE THREAD

**Issue by balthazar314** [BuiltBrokenModding/Assembly-Line#83]
I'm back, I downloaded the latest version of assembly line on curse and I'm using the volts engine version that works for the current ICBM. My game crashes at startup.
here's the log file.
[crash-2017-03-04_17.22.55-client.txt](https://github.com/BuiltBrokenModding/Assembly-Line/files/818992/crash-2017-03-04_17.22.55-client.txt)
I like the work you all are doing here

**Comment by DarkGuardsman** [comment]
Looks like I need to update assembly line on curse. Will do here later today or tomorrow. As well I will get @dmodoomsirius to setup some auto scripts to upload alpha versions.

**Comment by balthazar314** [comment]
Ah ok it works now thank you!
