### ISSUE TITLE
Rotation rail + chest cart = crash

### ISSUE THREAD

**Issue by JammerFTW** [BuiltBrokenModding/Assembly-Line#84]
http://pastebin.com/VsvQYFhb

mods installed: 

worldedit,
 warpdrive,
 VE,
 veinminer,
 translocator,
 thermal recycling,
 thermal foundation, expansion, and dynamics,
 techguns,
 supermultidrills,
 storage drawers,
 steves carts,
 StacksOnStacks,
 sonarcore,
 schematica,
 R.O.A.R,
 railcraft,
 projectE,
 progressive automation,
 practical logistics,
 pneumaticraft,
 optifine,
 OpenModularTurrets,
 openmodslib,
 openblocks,
 NEI,
 morph,
 MFR,
 MFFS,
 lunatriscore,
 Logistics pipes,
 IC2,
 inductive automation,
 IDT,
 iChunUtil,
 holoinventory,
 Funky locomotion,
 forestry,
 fastcraft,
 extrautilities,
 cofh core and lib,
 Code Chicken Core,
 Chisel,
 ChestTransporter,
 chance cubes,
 BC,
 BigReactors,
 BetterSleeping,
 BetterBuildersWands,
 AssemblyLine,
 ArchitectureCraft,
 Applied energististics,
 Advanced Inventory,
 Conveyor craft

**Comment by DarkGuardsman** [comment]
If I recall right this issue was resolved in Discord? If i'm wrong reopen.
